name: Security Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * MON'  # Run every Monday at midnight UTC

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache advisory database
        uses: actions/cache@v4
        with:
          path: ~/.cargo/advisory-db
          key: advisory-db
          
      - name: Run cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install cargo-deny
        run: cargo install --locked cargo-deny
        
      - name: Check licenses
        run: cargo deny check licenses
        
      - name: Check bans
        run: cargo deny check bans
        
      - name: Check advisories
        run: cargo deny check advisories
        
      - name: Check sources
        run: cargo deny check sources